version: "3"

vars:
  LSP_HOST:
    sh: echo {{.LSP_HOST | default "127.0.0.1"}}
  LSP_PORT:
    sh: echo {{.LSP_PORT | default "9090"}}

tasks:
  default:
    desc: Send test packets to LSP server via TCP
    cmds:
      - uv run --no-project python main.py {{.LSP_HOST}} {{.LSP_PORT}}

  send:
    desc: Send test packets to LSP server via TCP with custom host/port
    cmds:
      - uv run --no-project python main.py {{.LSP_HOST}} {{.LSP_PORT}}
