version: "3"

set: [set -e]

vars:
  PIPE:
    sh: echo {{.LSP_PIPE | default "/tmp/lsp_pipe"}}

tasks:
  default:
    desc: Send test packets to LSP server via FIFO
    cmds:
      - uv run --no-project python main.py {{.PIPE}}

  send:
    desc: Send test packets to LSP server via FIFO with custom pipe path
    cmds:
      - uv run --no-project python main.py {{.PIPE}}

  setup-pipe:
    desc: Create FIFO pipe for LSP communication
    cmds:
      - mkfifo -m 600 {{.PIPE}}
